export default {
  INIT: 'INIT',
  GET_LANGUAGE_ID: 'GET_LANGUAGE_ID',
  SET_LANGUAGE_ID: 'SET_LANGUAGE_ID',
  MUTATE_LANGUAGE_ID: 'MUTATE_LANGUAGE_ID',
  FETCH_I18N: 'FETCH_I18N',
  MUTATE_I18N: 'MUTATE_I18N',
  GET_I18N: 'GET_I18N',
};
