export default {
  INIT: 'INIT',
  GET_USER_AGENT: 'GET_USER_AGENT',
  MUTATE_USER_AGENT: 'MUTATE_USER_AGENT',
  GET_USER_BROWSER: 'GET_USER_BROWSER',
  MUTATE_USER_BROWSER: 'MUTATE_USER_BROWSER',
  GET_USER_OS: 'GET_USER_OS',
  MUTATE_USER_OS: 'MUTATE_USER_OS',
  GET_IS_MOBILE: 'GET_IS_MOBILE',
  MUTATE_IS_MOBILE: 'MUTATE_IS_MOBILE',
  GET_IS_AD_BLOCK: 'GET_IS_AD_BLOCK',
  MUTATE_IS_AD_BLOCK: 'MUTATE_IS_AD_BLOCK',
};
