export default {
  momentData: {
    temperature: null,
    humidity: null,
    pressure: null,
    rainfall: null,
    windVerticalSpeed: null,
    windSpeed: null,
    windDirection: null,
  },
  statData: {
    windSpeed: null,
    windHorizontalSpeed: null,
    windMaxSpeed: null,
    windDirection: null,
    dewPoint: null,
  },
  deviceData: {
    name: null,
    positionN: null,
    positionW: null,
    date: null,
    time: null,
    temperature1: null,
    temperature2: null,
    power1: null,
    power2: null,
    voltage1: null,
    voltage2: null,
  },
  sensorData: {
    windIsOnLine: true,
    rainIsOnLine: true,
    weatherIsOnLine: true,
    gpsIsOnLine: true,
    compassIsOnLine: true,
    battery1IsOnLine: true,
    battery2IsOnLine: true,
  },
};
