export default {
  RESET_STATE: 'RESET_STATE',
  FETCH_DATA: 'FETCH_DATA',
  GET_MOMENT_DATA: 'GET_MOMENT_DATA',
  MUTATE_MOMENT_DATA: 'MUTATE_MOMENT_DATA',
  GET_STAT_DATA: 'GET_STAT_DATA',
  MUTATE_STAT_DATA: 'MUTATE_STAT_DATA',
  GET_DEVICE_DATA: 'GET_DEVICE_DATA',
  MUTATE_DEVICE_DATA: 'MUTATE_DEVICE_DATA',
  GET_SENSOR_DATA: 'GET_SENSOR_DATA',
  MUTATE_SENSOR_DATA: 'MUTATE_SENSOR_DATA',
};
