export default {
  INIT: 'INIT',
  RESET_STATE: 'RESET_STATE',
  LOGIN_HANDLER: 'LOGIN_HANDLER',
  LOGOUT_HANDLER: 'LOGOUT_HANDLER',
  RE_LOGIN_HANDLER: 'RE_LOGIN_HANDLER',
  GET_USER_TOKEN: 'GET_USER_TOKEN',
  SET_USER_TOKEN: 'SET_USER_TOKEN',
  MUTATE_USER_TOKEN: 'MUTATE_USER_TOKEN',
  GET_USER_TYPE: 'GET_USER_TYPE',
  SET_USER_TYPE: 'SET_USER_TYPE',
  MUTATE_USER_TYPE: 'MUTATE_USER_TYPE',
};
