export default {
  FETCH_REPORT_FILE: 'FETCH_REPORT_FILE',
  GET_REPORT_TYPES: 'GET_REPORT_TYPES',
  SET_REPORT_TYPES: 'SET_REPORT_TYPES',
  MUTATE_REPORT_TYPES: 'MUTATE_REPORT_TYPES',
  FETCH_CHART_DATA: 'FETCH_CHART_DATA',
  GET_CHART_DATA: 'GET_CHART_DATA',
  MUTATE_CHART_DATA: 'MUTATE_CHART_DATA',
};
