export default {
  GET_REPORT_TYPES: 'GET_REPORT_TYPES',
  SET_REPORT_TYPES: 'SET_REPORT_TYPES',
  MUTATE_REPORT_TYPES: 'MUTATE_REPORT_TYPES',
  GET_REPORT_RANGE: 'GET_REPORT_RANGE',
  SET_REPORT_RANGE: 'SET_REPORT_RANGE',
  MUTATE_REPORT_RANGE: 'MUTATE_REPORT_RANGE',
  FETCH_CHART_DATA: 'FETCH_CHART_DATA',
  GET_CHART_DATA: 'GET_CHART_DATA',
  MUTATE_CHART_DATA: 'MUTATE_CHART_DATA',
};
