export default {
  RESET_STATE: 'RESET_STATE',
  FETCH_DATA: 'FETCH_DATA',
  FETCH_USER_LIST: 'FETCH_USER_LIST',
  CHANGE_MAIN_SENSOR: 'CHANGE_MAIN_SENSOR',
  GET_DEVICE_DATA: 'GET_DEVICE_DATA',
  MUTATE_DEVICE_DATA: 'MUTATE_DEVICE_DATA',
  GET_USER_DATA: 'GET_USER_DATA',
  MUTATE_USER_DATA: 'MUTATE_USER_DATA',
};
